### PR TITLE
WIP: shared delta batches tests

### PR DESCRIPTION
**Pull request by pgte**

### CODE REVIEW

**Comment by pgte** [comment]
@jimpick I've started the shared delta batches test setup here. Hopefully I've got enough in so that you can add the deltas so that, when (re)batched, they compromise the convergence.

**Comment by jimpick** [comment]
I'll add this tomorrow. (sorry, fighting a bit of a cold, so I'm slowing down)

**Comment by pgte** [comment]
rebased

**Comment by pgte** [comment]
@jimpick I've added some deltas, changed the test a bit and added a fix. Can you check this?

**Comment by jimpick** [comment]
I'm trying to recreate a scenario that matches the breakage I had in a bad trace...

I'm trying to reduce it down from 90 characters, as that is excessive, but I haven't quite managed to reproduce the behaviour exactly yet. I'll have to puzzle over it a bit more:

https://github.com/peer-base/peer-base/blob/cc387641a705a70c1a5ab3f6379aed6e8ead024e/test/shared-delta-batches.js#L69

I'm trying to match what happened in this trace:

https://github.com/jimpick/delta-crdt-ordering-demo/blob/master/debug7.out

I think I'm getting close, but it will take me a few more hours, I think.

**Comment by pgte** [comment]
@jimpick I'm very much inclined to merge this into master, as I believe is the correct theoretical approach to merging vector clocks. I've run the stress tests (in this repo and peer-pad's) and I haven't been able to break this (but I may not having your skills of being able to break peer-base). :)

Anyway, I think you have write access to this repo, so you should be able to open a PR with your changes to the test when you find a set of deltas that breaks (or used to break before f00b59d486bf13a423835426d45e45fc262f2a0d).

**Comment by jimpick** [comment]
Great! I think it's probably the right approach.

I'll continue working on trying to replicate my trace in a test ... then I will know for sure if this fixed the specific problem I observed.

I think that having a technique to generate a test from a trace will be handy in the future as we increase complexity.

**Pull request merged**
